### ISSUE TITLE
[Bug] Comptime causes out of bounds exception in ContiguousHeap 

### ISSUE THREAD

**Issue by RogueMacro** [beefytech/Beef#1004]
I tried debugging this, and it has been the source of many of my comptime crashes. I don't know exactly what is causing it to happen, but I'll attach my project (that should crash on open) and at line 178 in `Heap.cpp`, `mFreeIdx` is 4 while the size of `mFreeList` is just 4. After looking at the code I don't see how that is possible unless `mFreeList` changes size while iterating, but I don't know.

[Project.zip](https://github.com/beefytech/Beef/files/6429291/Project.zip)

**Comment by Fusioon** [comment]
Just had the same problem.. The problem seems to be that the `mFreeIdx` is reset before value is removed from the `mFreeList`. So if the `mFreeIdx` is the last value in the list, it won't be valid after the remove. https://github.com/beefytech/Beef/blob/58f669343453d2a46065f84c58c093b0d3073668/BeefySysLib/util/Heap.cpp#L183
I just copied this if block and pasted it after the `mFreeList.RemoveAtFast(mFreeIdx);`

**Comment by RogueMacro** [comment]
I tried this, which seemed to solve that problem. Now my problem is that (at comptime I guess) custom attributes aren't generated if there are non. So when I check to see if a field has this attribute, mCustomAttributes is null and crash.

**Comment by Fusioon** [comment]
Possible fix could be adding null check to the `CeContext::GetCustomAttribute`. 
```
if (!customAttributes)
	return false;
```
right at the start of the method.

**Comment by bfiete** [comment]
Fixed at e3db26004b85c591b1fea24269b75904f03f198e
Also fixed the custom attribute crash at b122655a464ba908cde704f656c09cf1e9056e4b
