### ISSUE TITLE
Generic function returning wrong type

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#108]
Using the GetProperty function it returns the wrong branch, causing compile errors.
When checking it in the debugger with FindType it picks the correct branch, confusing?

```
let value1 = GetProperty<float>("empty");
let value2 = GetProperty<bool>("empty");
let value3 = GetProperty<StringView>("empty");

public static T GetProperty<T>(StringView keyId)
	where T : var
{
	if (typeof(T) == typeof(int))
		return 0;
	else if (typeof(T) == typeof(float))
		return 0f;
	else if (typeof(T) == typeof(bool))
		return false;
	else if (typeof(T) == typeof(StringView))
		return "";

	return default;
}

public static StringView FindType<T>() where T : var
{
	StringView result = String.Empty;

	if (typeof(T) == typeof(int))
		result  = "int";
	else if (typeof(T) == typeof(float))
		result  = "float";
	else if (typeof(T) == typeof(bool))
		result  = "bool";
	else if (typeof(T) == typeof(StringView))
		result  = "StringView";

	return result;
}
```

**Comment by damianday** [comment]
On closer inspection GetProperty evaluates all possible return values, even when the value is not returned.

**Comment by damianday** [comment]
Nevermind, this bug report is invalid. I couldn't see the problem right in front of me, why I was expecting it to work like a compile time construct I don't know.

I'll try and find a more elegant solution to avoid code duplication.

**Comment by bfiete** [comment]
Yes. This is by design- even when an 'if' can be statically proven to be 'false', the actual 'true' path must not contain any errors.. it is still evaluated even though no actual machine instructions are generated.

You're expecting something like D's "static if" conditional compilation, which is something I've considered but haven't really decided on.

As it stands, "GetProperty" would only work with a T that has implicit conversion operators from int, float, bool, and StringView - even though those operators would not actually ever be invoked.

**Comment by bfiete** [comment]
Also- with the actual example you gave, "return default;" would actually handle all those cases :-)
