### ISSUE TITLE
Returning errors from constructors

### ISSUE THREAD

**Issue by rumbu13** [beefytech/Beef#11]
Since Exceptions are not available:
- how do I report an error from a constructor?
- how do I know if a constructor executed successfully?

For example, I looked into your DateTime implementation and constructors with out of range parameters call Runtime.FatalError(), which is not recoverable.

**Comment by bfiete** [comment]
The DateTime functionality has been lifted from C# and is not properly Beef-ified. Much of it is also not properly cross-platform -- it's in need of heavy modification or replacement.

Constructors cannot recoverably fail. If you want to fail then you need Init methods.

**Comment by rumbu13** [comment]
Regarding Beef-ification, can you recommend some idioms? 
I am thinking at something like static methods named e.g. Result<SomeStructType> TryConstruct()

**Comment by bfiete** [comment]
If it's a struct, then the idiom would be to have a static "Create" method. I generally don't prefix a "Try" for things that may fail, that's just inferred from the return type.

If it's a class that requires allocation then you really don't want static methods that allocate things, because that removes the ability of the user to control how allocation occurs (most importantly, it disallows stack allocation). In that case I generally I would just allow things to have a "default" or "uninitialized" state and then have separate Init methods to initialize it.
