### ISSUE TITLE
Frequent random crashes

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#1139]
[Crash dump](https://github.com/beefytech/Beef/files/7041684/random_crash.zip), otherwise nothing much to add, I'm unable to isolate the issue as the project is pretty large. I could also send the whole project if that would help.

**Comment by bfiete** [comment]
This might be fixed at 6df69a7d95a247be96a6ae9f8048017dd9af479e 

Whole projects are great so I can get a deeper view into the root cause of issue and also verify that the fix actually addresses the real problem rather than just fixing a symptom of the real problem You can email workspaces to beef@beefytech.com or just attach them to bug reports if you don't mind them being public.
