### ISSUE TITLE
Cannot pass regular parameters as ref

### ISSUE THREAD

**Issue by rumbu13** [beefytech/Beef#12]
static void SomeRef(ref int i) { }

static void NoRef(int i)
{
    SomeRef(ref i);
}

"Cannot use 'ref' on parameter 'i'. Consider adding 'ref' specifier to parameter or copying to a local variable"

This is valid syntax in C#, probably the parameter is shadowed on stack if not already passed on stack.

---

Later edit: Later I saw that this is a direct consequence of the fact that value parameters cannot be used inside a function:

void SomeFunc(int i) { i = 0; } //=> error.

**Comment by bfiete** [comment]
Parameters are immutable. In C#, value types are always copied, including large structs, but in Beef structs can be passed by const reference OR by value (compiler's choice, depending on data layout).

There's a syntax shorthand for creating a mutable copy of a parameter:
```
static void NoRef(int i)
{
	var i;
	SomeRef(ref i);
}
```
When you step through this in the debugger, you can see the original shadowed immutable value as well as the mutable copy. This is useful because you will always be able to see what values were actually passed into the method you are debugging.

The optimizing compiler will be able to optimize the copy away in many cases.
