### ISSUE TITLE
Crash while compiling code with some `const` variables

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1225]
The below code crashes while compiling, if you remove both `const` qualifiers it compiles but returns the wrong value, it only works as expected if you add the `Comptime` Attribute to the `TestVar` method.
```cs
		public static int32 TestVar<T>() where T : var
		{
			const let type = typeof(T);
			const let isVoid = type == typeof(void);

			if (!isVoid)
			{
				return type.IsTuple ? type.FieldCount : 1;
			}

			return -1; // always shows the unreachable warning
		}

		[Test]
		public static void TestBug()
		{
			Test.Assert(TestVar<(int, String)>() == 2);
		}
```

**Comment by bfiete** [comment]
Unreachable issue fixed at 048c1c1ab8650e1d1fc4db57b7142f939fb462d1
Crash fixed at a7da8a75d69f1ec6826e3450065f4e73642f6cd8 - fingers crossed that doesn't cause a const regression elsewhere

The FieldCount is wrong because tuples do not have reflection information - and they can't, since there's no way to set `[Reflect]` on it.

**Comment by disarray2077** [comment]
> The FieldCount is wrong because tuples do not have reflection information - and they can't, since there's no way to set `[Reflect]` on it.

But isn't this being resolved at compile-time, as `type` is const?

**Comment by bfiete** [comment]
Nope, that's all runtime. The `const` just refers to the fact that you're pointing to a global variable (the runtime reflection data).

**Comment by bfiete** [comment]
It's only comptime if the actual `type.FieldCount` is evaluated at comptime

**Comment by disarray2077** [comment]
I see, so `const int fieldCounts = typeof(T).FieldCount;` should work.

**Comment by bfiete** [comment]
I didn't handle virtual method comptime entrypoints because it's not possible to create a const class instance that you could invoke it on anyway .... except for a `System.Type` instance or a string. So `FieldCount` invoked `Type.FieldCount get` instead of `TypeInstance.FieldCount get`, thus the zero result.

Most reflection properties can const-evaluate, but I didn't bother supporting `FieldCount` because then the const evaluation wouldn't necessarily match the actual runtime value. Also it's not a very useful value by itself without the actual enumerated fields...

Will throw an error at 6874402e58889179c618e7130c0bd33ef18a3837
