### ISSUE TITLE
Error building on Arch

### ISSUE THREAD

**Issue by Gabisonfire** [beefytech/Beef#128]
Hi,
Trying to build 0.42 on Manjaro, I had to install libbacktrace from the link you provided in another issue (https://github.com/ianlancetaylor/libbacktrace.git) and I'm still getting this error:

```
Linking BeefBuild_bootd.../usr/bin/ld: ./libBeefRT_d.a(LinuxCommon.cpp.o): in function `full_callback(void*, unsigned long, char const*, int, char const*)':
/home/gabisonfire/Downloads/Beef/BeefySysLib/platform/linux/../posix/PosixCommon.cpp:343: undefined reference to `backtrace_syminfo'
/usr/bin/ld: ./libBeefRT_d.a(LinuxCommon.cpp.o): in function `simple_callback(void*, unsigned long)':
/home/gabisonfire/Downloads/Beef/BeefySysLib/platform/linux/../posix/PosixCommon.cpp:350: undefined reference to `backtrace_pcinfo'
/usr/bin/ld: /usr/lib/libbacktrace.so.0: undefined reference to `backtrace_alloc'
collect2: error: ld returned 1 exit status
FAIL: Exit code returned: 1

FAILED
```

Any ideas?

**Comment by linkpy** [comment]
Hello there.

I had the same issue but it was quickly fixed. 

https://github.com/beefytech/Beef/blob/d6a4b8b62c9472cfac26a7dc33c539f06f8bd827/bin/build.sh#L64
At the end of the line, before `$LINKOPTS` i simply added `/usr/lib/libbacktrace.a` and the compilation worked.

**Comment by Gabisonfire** [comment]
@linkpy Thanks that helped me progress a bit. Now another error comes up:

```
Building BeefBuild_bootd
[******************************]
TIMING: Beef compiling: 18.7s
Linking BeefBuild_bootd...
SUCCESS
Building BeefBuild_d
[******************************]
Beef compilation time: 22.80s
/usr/bin/ld: /usr/lib/libbacktrace.so.0: undefined reference to `backtrace_alloc'
/usr/bin/ld: ./libBeefySysLib_d.so: undefined reference to `backtrace_pcinfo'
/usr/bin/ld: ./libBeefySysLib_d.so: undefined reference to `backtrace_syminfo'
collect2: error: ld returned 1 exit status
Execution Failed
ERROR: BUILD FAILED
```

**Comment by linkpy** [comment]
I didn't have that error when i built it. It seems like you are using the dynamically linked libbacktrace (\*.so), and i used the statically linked one (\*.a). You can also try adding `/usr/lib/libbacktrace.so` for `BeefBuild_d` too (the line with `--out="BeefBuild_d"` argument).

Finally if it doesn't work, you should do `nm /usr/lib/libbacktrace.so.0 | grep backtrace` and check if `backtrace_alloc`, `backtrace_pcinfo` and `backtrace_syminfo` are shown. If not, the issue comes from your libbacktrace which isn't of the right version (has it doesn't have these functions inside).

**Comment by Gabisonfire** [comment]
Thanks a lot @linkpy , I got it to build! I ended up remove the lib I had installed from the sources and used the one on AUR, plus adding the params you suggested. Thanks a lot for your help!
