### ISSUE TITLE
[Bug] Moving text cursor up/down with selection active

### ISSUE THREAD

**Issue by m910q** [beefytech/Beef#1305]
When text is selected, moving the text cursor up or down with the keyboard results in moving the cursor to the beginning of the line it goes to.

I expect it to go to the nearest possible horizontal location from where the cursor currently is. Like it does when no selection is made.
This is also the default behavior in other editors.

**Comment by bfiete** [comment]
Fixed at 905ccae64c06e6d045ed259a32a38d78867633f1

Interesting, it appears that there's a bug in VS2019 with this: if you use the mouse to make the selection (below) and then press up, then the cursor is placed before the 'R' on the line above, but if you make the selection with the keyboard then the cursor is placed before the 'E' (the expected behavior described in this bug report)
![image](https://user-images.githubusercontent.com/3042917/147466958-775ab172-7fdb-41c6-b620-39ff6d3ad0d9.png)

**Comment by m910q** [comment]
Just tried in VS 2022, and using mouse for selection indeed makes it very weird.

Selection from start to end of selection act as if the cursor is in the beginning, even though it's in the end.
Selecting from end to start, makes it use the "end" position, even though it should use the start. But it still goes to the corret line if you have miltiple lines selected.
If they switch start/end position horizontally, it would work correctly. Or just used the actualt cursor position which is shown correctly.

But nice that it's fixed in Beef!
