### ISSUE TITLE
[Enhancement] Comptime should be asynchronous

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1329]
I don't think it's good to have comptime stopping IDE functionality, but the code below causes the IDE to hang and become extremely slow, so if comptime was asynchronous this wouldn't be an issue... Not sure if this is viable though. But I guess the IDE at least shouldn't hang.

```cs
using System;
using System.Diagnostics;
using System.IO;

namespace test6
{
	class Program
	{
		[Comptime]
		public static void Test()
		{
			let startInfo = scope ProcessStartInfo();
			startInfo.SetFileNameAndArguments("ping 127.0.0.1 -n 10");
			startInfo.UseShellExecute = false;
			startInfo.RedirectStandardOutput = true;
			startInfo.CreateNoWindow = true;

			let proc = scope SpawnedProcess();
			if (proc.Start(startInfo) case .Err)
				return;

			let output = scope FileStream();
			let sr = scope StreamReader(output);
			proc.AttachStandardOutput(output);

			for (int i = 0; i < 10; i++)
				sr.ReadLine(.. scope .());
		}

		public static int Main(String[] args)
		{
			Test();

			return 0;
		}
	}
}
```

**Comment by bfiete** [comment]
Comptime is async, BUT there's two issues:
1) There are sync points during typing with autocomplete in order to have deterministic results (ie: typing `a.b` should always insert the autocomplete results from `a` when entering the `b`). The IDE needs to be refactored to have an input queue that we can leave events in (ie: when pressing the `.` when the `a` results haven't come back yet). Not extremely hard, just work.
2) Comptime methods are all supposed to be either fast or cancelable, but `BfpFile_Read` on non-waitable files (ie: unnamed pipes) couldn't be canceled. That is fixed in 1201289f78ea1597c3dc1fe088a0ef7e4abcab7b, which should fix the observed problem but without fixing the other underlying issue mentioned above in #1
