### ISSUE TITLE
cannot get member reflection info on Array and List<>

### ISSUE THREAD

**Issue by EinScott** [beefytech/Beef#1410]
I'm not completely sure if i'm just missing something here, but this looks like it *should* provide me with reflection info for Array and List<>.

```cs
[AttributeUsage(.Class|.Struct|.Enum, .AlwaysIncludeTarget, ReflectUser = .AllMembers | .DefaultConstructor, AlwaysIncludeUser = .AssumeInstantiated)]
struct SerializableAttribute : Attribute {}

namespace System
{
	[Serializable]
	extension Array1<T> {}

	[Serializable]
	extension Array {}

	namespace Collections
	{
		[Serializable,Reflect(.Methods)]
		extension List<T> {}
	}
}

namespace BfTest {
	class Program
	{
		static void Main()
		{
			Runtime.Assert(typeof(uint8[]).GetField("mFirstElement") case .Ok); // Array1<> has no problem

			Runtime.Assert(typeof(List<int>).GetMethod("EnsureCapacity") case .Ok); // Should be forced by Reflect? -> .Methods
			Runtime.Assert(typeof(List<int>).GetField("mSize") case .Ok); // Should be forced by Serialize? -> .AllMembers
			Runtime.Assert(typeof(uint8[]).GetField("mLength") case .Ok); // Should be forced by Serialize? -> .AllMembers

			Console.Read();
		}
	}
}
```

**Comment by disarray2077** [comment]
I guess Attributes on extensions don't actually work currently, there's even an issue about this: https://github.com/beefytech/Beef/issues/1037

**Comment by EinScott** [comment]
Yea i know about that one, but forcing reflection this ways has still worked (the first assert actually passes). I didn't metion it here, but as with #1399, using the build settings also doesnt seem to work.
![grafik](https://user-images.githubusercontent.com/38580263/152476751-7767fd53-8c5c-4f8e-9240-e3739c489ae6.png)

**Comment by bfiete** [comment]
Well, there is that https://github.com/beefytech/Beef/issues/1037 bug, which is fixed at 361be9dc92103be9b16b3b81b429cc477f735af6

But also:

Just to be clear on these distinct build settings from the image you posted- your settings say:
1) Assume these types are instantiated (meaning include the vtables and default ctor)
2) Reflect all included non-static fields
3) Reflect all included non-static methods
4) Reflect on any included methods named "EnsureCapacity" (already included from the previous non-static methods filter)

You needed to set the "Always Include" setting to "Include All" rather than "Assume Instantiated" to force `EnsureCapacity` to be included in the build, otherwise you're only specifying you want reflection _if_ the method gets included in the build.

I've added a new "Always Include" of "Include Filtered" to give an option to only force inclusion on the methods that match the filters (and of course they get reflected as well).

In your code example, in `SerializableAttribute` you did not use `AlwaysIncludeUser = .All` and the `EnsureCapacity` method wasn't included in the build so that's why you didn't find it.

**Comment by EinScott** [comment]
Ah thanks. For some reason I was under the assumption that EnsureCapacity *was* included and i apparently didn't think too hard about it... some Add()->(calls EnsureCapacity) func is called != Add() is called on *this* specialized type of list. Works now with IncludeFiltered, much appreciated!

**Comment by EinScott** [comment]
i think i'm encountering an issue with includeFiltered. I'm including TryAdd and Remove on System.Collections.Dictionary<*,*> in bon's (project bon in the workspace) build settings.
Currently i do IncludeAll, switching to IncludeFiltered should reproduce. Running the tests should fail at some point: https://github.com/EinScott/bon
