### ISSUE TITLE
Unable to build on Ubuntu 18.04

### ISSUE THREAD

**Issue by HelloWorldGuy12** [beefytech/Beef#144]
While compiling from source I got this error. How can I fix it?
https://pastebin.com/RGcHkanP

**Comment by CPUFronz** [comment]
I guess it's because LLVM wasn't build correctly. 

I had the same problem when I ran out of disk space during the compilation of LLVM. Run [llvm_build.sh](../blob/master/extern/llvm_build.sh) again and make sure that you have enough free space available (LLVM needs around 27 GB to be compile).

Then try to build again.

**Comment by HelloWorldGuy12** [comment]
I'll try that, thank you

**Comment by CPUFronz** [comment]
I checked again: it's probably more than 27 GB. It's probably better to have around 40 GB free for building Beef.
