### ISSUE TITLE
Please rename the language

### ISSUE THREAD

**Issue by raizam** [beefytech/Beef#145]
how about **protein**? :)

**Comment by GH-TheRaven-06835** [comment]
my vote is for: beef vegetable
I just had to -- forgive me.

**Comment by Bigalan09** [comment]
B#

**Comment by sukhchain99** [comment]
Don't want to be disrespectful but, You guys are idiots. Do you even know how much time it will take to rebuild the fame and all the search results with the name of the language will be gone. Just changing the Logo/Icon should suffice. GameFromScratch has featured Beef in one of his latest videos and it has increased traction to the project. Changing name is unnecessary, but changing the Logo is really necessary because of the copyright problems and the logo potrays the wrong image of the language. The first time I found this project I didn't want to even consider checking it out because of the Logo, the Logo is childish and because of it the project seems unprofessional at the first glance.

**Comment by bfiete** [comment]
There's already a discussion here https://github.com/beefytech/Beef/issues/14

**Comment by julcreutz** [comment]
@sukhchain99 What's wrong about the logo? I disagree with you that it's childish. I like it.
