### ISSUE TITLE
Spurious data dependency during TypeInit error

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1599]
The below code results in the `OnCompile const evaluation creates a data dependency during TypeInit` error, but only sometimes after you do a clean build.
```cs
namespace System
{
	extension Enum
	{
		[Comptime]
		public static int GetCount<T>() where T : enum
		{
			int i = 0;
			for (let v in GetValues<T>())
				i += 1;
			return i;
		}
	}
}
```
Tested with 48571d374fb68d853a0d930175e48d19caf50c9c

**Comment by bfiete** [comment]
Fixed at 0e86b5c49db21ee5463b738c3bf5f06112a50ce3

**Comment by bfiete** [comment]
This gave me some ideas for some comptime improvements.

Check out https://github.com/beefytech/Beef/blob/master/BeefLibs/corlib/src/Enum.bf#L8 `Count`, `MinValue`, `MaxValue`

Instead of `Enum.GetCount<SomeEnum>()`, you can do `SomeEnum.Count`. The key is `Compiler.OrigCalleeType`. 
`SomeEnum.MinValue` and `SomeEnum.MaxValue` are non-generic properties but they can dynamically specify a comptime return type via `Compiler.SetReturnType`

**Comment by bfiete** [comment]
Good point. They are methods now @ 439b34f7c25f8987259860490fea0b6be786ee9c
