### ISSUE TITLE
Stomp allocator causing EXCEPTION_ACCESS_VIOLATION in appended String contructor

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#1647]
Code to reproduce:
```bf
class Program
{
    class Foo
    {
        public String _name ~ delete:append _;
        public String _help ~ delete:append _;

        [AllowAppend]
        public this(StringView name, StringView help)
        {
            String tmpName = append String(name);
            String tmpHelp = append String(help);
            _name = tmpName;
            _help = tmpHelp;
        }
    }

    public static void Main()
    {
        let f = new Foo("aaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
        delete f;
    }
}
```
This code crashes at runtime when `String` constructor from line `String tmpHelp = append String(help);` calls `MemCpy`. but only when workspace allocator is set to `Stomp`. 
When i make the first param longer or second shorter it somehow works. 

Tested with: Nightly 07/10/2022

**Comment by bfiete** [comment]
Fixed at b2b964489ef8623e5d2c4782cf5b366546b67892

It really was just a stomp allocator issue - because the stomp allocator ignores the requested alignment, but then the `Foo` ctor still tries to align the append allocations -- but the actual allocated buffer size was calculated with the assumption that the allocated buffer would had a specific alignment, which ends up being too small when it ends up _not_ being aligned.
