### ISSUE TITLE
Casting from a bigger enum to a smaller one results in an incorrect value

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1661]
When `EnumB.Δ` is converted to `EnumA` the underlying value of `EnumB.Δ` is 44 instead of 300.
I guess Beef's enum optimization causes this, so maybe we could at least have a warning when this happens.

Repro code:
```cs
enum EnumA
{
	A,
	B,
	C
}

enum EnumB
{
	Δ = 300,
	Ω,
	β
}

const EnumA Δ = (EnumA)EnumB.Δ;

public static void Main(String[] args)
{
	Compiler.Assert((int)Δ != 44);
	Compiler.Assert((int)Δ == 300);
}
```
Tested with: https://github.com/beefytech/Beef/commit/119e9189e5cc41c747b2af01abbb87966cb6b422

**Comment by bfiete** [comment]
Well, you _did_ perform an explicit cast, which is generally the thing that would remove a range warning if there were one...

What about explicitly casting from an `int` to an enum - should that _always_ produce a warning since an int will almost always be larger than the underlying enum type?

It seems that storing out-of-range values in an enum is a bit of an edge case and you just have to explicitly specify the underlying type if you want to do that... I don't really see a cleaner way to handle it.

**Comment by disarray2077** [comment]
> Well, you _did_ perform an explicit cast, which is generally the thing that would remove a range warning if there were one...
> 
> What about explicitly casting from an `int` to an enum - should that _always_ produce a warning since an int will almost always be larger than the underlying enum type?

🤔... Yeah, I didn't think this well enough.


> It seems that storing out-of-range values in an enum is a bit of an edge case and you just have to explicitly specify the underlying type if you want to do that... I don't really see a cleaner way to handle it.

I agree. This actually came up while I was converting some C# code but even in C# this is an edge case, I guess there's no point in doing anything differently. The best solution to this really seems to be using a larger underlying type.
