### ISSUE TITLE
Destructor for ValueTypes

### ISSUE THREAD

**Issue by FlaXxy1** [beefytech/Beef#176]
What was the design idea to not have destructors for structs?
You follow the idea of RAII style a little bit with scoped allocations. Why not follow all the way and have a destructor for every object, when out of scope?

And what about calling destructors of ValueType-members of an object?

**Comment by bfiete** [comment]
The pattern is to define a Dispose method that you call manually.

The reason there's no automatic destructors is the same reason C# doesn't have them: because down that road lies C++ with copy constructors, assignment operators, rvalue references, move semantics, perfect forwarding, etc.

Beef presents struct struct data as more C POD-style, and you get the benefits of simplicity that comes with that.
