### ISSUE TITLE
[Bug] Memory corruption with incremental builds

### ISSUE THREAD

**Issue by MineGame159** [beefytech/Beef#1793]
Simply running the startup project should trigger an exception while it is starting up, if it doesn't happen try changing the workspace level allocator.

Project: [meteorite.zip](https://github.com/beefytech/Beef/files/10714930/meteorite.zip)
List of dependencies that the attached project requires: https://github.com/MineGame159/meteorite#dependencies

EDIT: Switching between Debug / Release modes also seems to trigger it.

**Comment by bfiete** [comment]
Hm, well, this is fixed at cb177bc7592c8ab457de3bdfc9241975f5200bba

It doesn't seem like it should have caused the issue in your video you posted on Discord since this was only related to sized arrays with object element (not enums), but I tried to reproduce the issue you posted there and I couldn't (even without the fix applied).

Maybe try that test case again and post some instructions or and possibly an updated project explaining how to reproduce that if it's still happening...

**Comment by MineGame159** [comment]
Thanks for the fix, will try it when a new nightly comes out.

And if I understand correctly then this fix applies to my video too since in it the array element was a dictionary which contained the enum.

**Comment by bfiete** [comment]
Oh yeah you're right, I was being dumb thinking about `Bar` and `DescriptorType`.
