### ISSUE TITLE
[Bug] Very slow compilation

### ISSUE THREAD

**Issue by MineGame159** [beefytech/Beef#1797]
Normally a clean build of my project takes ~10 seconds on my machine but with my [latest commit](https://github.com/MineGame159/meteorite/commit/63973860ee25df3371438c805ecd5117bd0860ae) a clean build takes 80 - 150 seconds.
When doing an incremental build the compile time depends on which classes were modified. For example adding `Console.WriteLine();` to the constructor of [ResourceKey](https://github.com/MineGame159/meteorite/blob/master/src/World/Registry/ResourceKey.bf) takes a very long time (anywhere between a few seconds to the time it takes to do a clean compile) to compile, but adding the same code to [Program](https://github.com/MineGame159/meteorite/blob/master/src/Program.bf) only takes ~0.2 second.

Project: https://github.com/MineGame159/meteorite
The Beef dependencies required for the project are listed inside the README.

**Comment by bfiete** [comment]
The big `Meteorite.Blocks.Register()` and `Meteorite.Items.Register()` are the issue. The problem is that you're allocating strings on the stack there now and it's causing some huge register contention on the backend, which is technically a backend issue but that's not likely to be changed anytime soon.

For `AIR = Register(new .(scope .("minecraft:air"), 0, scope ItemSettings()));`, there's no reason at all to use `scope .("minecraft:air")` instead of just `minecraft:air`. You're just creating a local copy of that string literal and then the `Items` constructor ALSO allocates an append-allocated string that the scoped string gets copied into.

Also consider not passing in `scope ItemSettings()` and have a constructor that doesn't take the ItemSettings that can use default values.

Actually, I would just rewrite `AIR = Register(new .(scope .("minecraft:air"), 0, scope ItemSettings()));` as `AIR = Register("minecraft:air", 0);` and have the `Register` method do even the heap allocation.

**Comment by MineGame159** [comment]
Ah, yeah there are a few auto generated monster classes. Thanks for looking at the project, I am gonna try to optimize them.
