### ISSUE TITLE
LLVM codegen issue on Linux

### ISSUE THREAD

**Issue by gw3583** [beefytech/Beef#18]
Trying to get a sense of how much work is involved in getting the IDE GUI to run on Linux. I hacked out all the compile errors, but I then get an LLVM error when I try to build. Steps to reproduce:

* Check out https://github.com/gw3583/Beef/tree/ide-hack on Linux (has the compile errors hacked out + the linux build script improvements).
* Build via `bin/build.sh`
* Manually run `./IDE/dist/BeefBuild -proddir=IDE -clean -config=Debug_NoDeps`

The output I get is:

```
[*****************Call parameter type does not match function signature!
i8* %0
 i32  %4 = call i32 @BfpSystem_SetCommandLine(i8* %0, i8* %1)
in function WinMain
LLVM ERROR: Broken function found, compilation aborted!
```

**Comment by bfiete** [comment]
I suspect this is because the Target Type in the IDE's General/Project properties is "Windows Application".  Really that should be generalized into a "GUI Application", but anyway- I think if you set that to "Console Application" then it'll probably fix that error.

Getting the editor working would be step one. All the DirectX and Windows-related support in BeefySysLib/platform/win would need a Linux equivalent. There is SOME OpenGL support in BeefySysLib/platform/sdl, but it has been unused for some time, and the other SDL support code in there is not low-level enough for all the windowing support required.

Then there are some Windows-specific things in the IDE like file dialogs, that would have to be made more cross-platform.

Then there's the issue of the Debugger. That is very Windows-specific. You can see the general debugger interfaces required in IDEHelper\Debugger.h, and theoretically that can drive a GDB or LLDB session, but... only theoretically at the moment.

Overall I would consider it quite a hefty task. I would be quite impressed to see the IDE editor working at all in Linux!

**Comment by gw3583** [comment]
Yup, changing `TargetType` in the `BeefProj.toml` to `BeefConsoleApplication` does get past that error, thanks. Now there are a heap of link errors, which isn't super surprising.

I don't imagine I'll actually make any real progress, but I figure it's an interesting way to learn a bit about the project and what state Linux support is in :smile:
