### ISSUE TITLE
Large memory leak

### ISSUE THREAD

**Issue by Moneyl** [beefytech/Beef#1815]
I'm getting a large memory leak when typing in certain files in one of my projects. Memory usage grows proportionally with how much is typed. The first few times this happened I ran out of memory and it either caused a bunch of applications to crash or one time crashed my entire computer. Now that I'm aware of the issue it's more of a nuisance that I can easily work around.

Steps to reproduce:
- Clone this: https://github.com/Moneyl/Nanoforge
- Run `git submodule update --init --recursive` in the repos root directory
- Open the Nanoforge workspace in the Beef IDE.
- Find the RfgTools library in the workspace panel, open `RfgTools/Formats/Meshes/Terrain.bf`, and start spamming the keyboard. You should see memory usage rise quickly in task manager.

**Comment by Moneyl** [comment]
This is present in ef9464900ec22e4344366badee8e51b709238f11 and has been an issue for at least a month. I don't know the commit where the issue emerged yet.

**Comment by bfiete** [comment]
Good find, that's a really bad one.

Fixed at 27a00b64ba22ca7bcd701a94263a67634323bd56

**Comment by bfiete** [comment]
Oh also I should note- you did have one case where you ended up with an issue because of the lambda changes I mentioned here: https://discord.com/channels/670260150656827422/670260151130914818/1086314603799121961

You had a local variable lambda capture with a `[&]` that gets retained past the lifetime of the local variable scope. Previously that _didn't_ actually get captured by reference, but now it does, so you can just use `[?]` in that location to get the old behavior and avoid that crash.

Also, it looked like `Zlib` was added by name to the project (ie: Add From Installed) rather than by path so I wasn't able to load the workspace at first. And you do have a hard-coded `c:\Users\` save path in there that causes an issue on not-you people's machines.

**Comment by Moneyl** [comment]
Thanks for pointing those out. They should be fixed now. Ended up changing `Nanoforge.Workspace` to use comptime to set the path instead of a file generator. If you ever try to test it on the game you'll also need to change the data folder path in `Nanoforge/src/Systems/AppLogic.bf`. I didn't port the selector UI yet.
