### ISSUE TITLE
Upgrading LLVM to 10.0? 

### ISSUE THREAD

**Issue by ChlorineX** [beefytech/Beef#195]

**Comment by Skrylar** [comment]
I tried naively doing this by just installing the llvm10 devel package on Tumbleweed but it gave an array of syntax errors. Would have to look in to it further to see if its being fussy about GCC.

**Comment by bfiete** [comment]
Just curious - was there something specific in 10.0.0 that you want/need?

**Comment by ChlorineX** [comment]
I suppose that there will be some optimizations of the backend and optimizer, which can generate faster code. I'm not a expert in this. I just saw that both rustc and ldc uses llvm 10.

**Comment by bfiete** [comment]
We'll upgrade periodically, but an upgrade is not free - the LLVM API is not stable, new LLVM releases can also introduce new bugs that we need to be on the watch for, and it requires everyone building from source to build a new LLVM. But yes it will happen occasionally.

**Comment by ChlorineX** [comment]
Thanks for explaining.

**Comment by AntyMew** [comment]
Bumping; llvm 10 is the earliest version I can build on my machine (debian bullseye).

[MicrosoftDemangleNodes.h](https://github.com/llvm/llvm-project/blob/llvmorg-8.0.0/llvm/include/llvm/Demangle/MicrosoftDemangleNodes.h) fails to build because it doesn't include `cstdint` and `string`. Adding the includes manually fixes the issue, and the first 10% of the build after that has gone fine.

**Comment by bfiete** [comment]
I was planning on jumping straight ahead to 11.0 when that releases, which should be very soon.
