### ISSUE TITLE
How do I use function from static library?

### ISSUE THREAD

**Issue by Argentoz** [beefytech/Beef#254]
How do I use GetProcess from class?
![image](https://user-images.githubusercontent.com/35398135/81798408-afd5ce80-9518-11ea-8b4c-c3de06fed54e.png)
It's not working: 
![image](https://user-images.githubusercontent.com/35398135/81799142-9719e880-9519-11ea-9f3d-b012f048348d.png)
Error: `fatal error LNK1120`
It's working:
![image](https://user-images.githubusercontent.com/35398135/81801260-caaa4200-951c-11ea-9535-e8c65e543f6d.png)
It is very inconvenient to use functions from classes.

**Comment by bfiete** [comment]
I think you're asking how do you CREATE a static library in Beef and then use it in a different Beef application? 

You cannot create a static library in Beef, this is not supported (at least not at this time). Precompiled libraries must be DLLs, and then you can [Export] methods. Is there a particular reason you want to create a static precompiled lib that you link to later rather than just including the lib in the workspace like normal?

**Comment by Green-Sky** [comment]
I think he is trying to **import** a c++ static method, with demangling getting in the way.

**Comment by bfiete** [comment]
Ah yes I missed that part.
There's new functionality (will be in 0.42.4) which allows for this:
`
[StdCall, LinkName(.CPP)]
public static extern bool GetProcess(uint32* pID);
`

But unfortunately a DWORD is 'unsigned long' whereas uint32 is 'unsigned int' which do not mangle the same.
