### ISSUE TITLE
Generic structs cannot have their pointers stored

### ISSUE THREAD

**Issue by LoopyAshy** [beefytech/Beef#255]
Simply when the generic type is a struct if you create the object on the heap it will create a pointer however the compiler believes this value to be a none-pointer as if it was class being created on the heap and as such the pointer cannot be used at all (if you use & it will create a int** for example instead and you cannot deference it as it believes it is not a pointer).

basically it behaves as though all generics are classes.

**Comment by bfiete** [comment]
If you want a generic that only operates on value types then you can specify that in the constraints
```C#
public static void Test<T>() where T : new, struct
{
	T* val = scope T();
	*val = default;
}
```

If you want a single generic that operates on both value types and reference types then you can do
```C#
public static void Test<T>() where T : new, delete, IPrintable
{
	var val = new T();
	val.Print(scope String());
	delete val;
}
```

The bug is that unconstrained generic allocations are assumed to resolve to "T" when in reality they may resolve to "T*" when specialized by a value type. But the use of var/let will abstract away the type.

**Comment by bfiete** [comment]
This is resolved in https://github.com/beefytech/Beef/commit/9d5d5b4063f309b28b19196e7630d63bcf31daab

There's now an `alloctype(T)` when we're not constrained by either struct or class.
