### ISSUE TITLE
Import of class constructor from static library

### ISSUE THREAD

**Issue by Argentoz** [beefytech/Beef#285]
I can't import a class constructor from static library.
![image](https://user-images.githubusercontent.com/35398135/82523594-559ac600-9b35-11ea-889d-eeb1fc11bd14.png)
What the Beef compiler is outputting:
`?__BfCtor@TestLibrary@testlib@bf@@QEAAXXZ`
What the c++ compiler is outputting:
`??0TestLibrary@testlib@@QEAA@XZ`
C++ class:
![image](https://user-images.githubusercontent.com/35398135/82523568-49166d80-9b35-11ea-8c39-961e3dd99188.png)
LinkName isn't working:
![image](https://user-images.githubusercontent.com/35398135/82523639-7531ee80-9b35-11ea-804c-e56692b41a72.png)

**Comment by bfiete** [comment]
There's a little more information about interop here: https://www.beeflang.org/docs/language-guide/interop/

**Comment by bfiete** [comment]
That being said, if you are absolutely set on wrapping a C++ class, then I suppose there should be a way to do it.  You would have to do it with a struct, however, and then LinkName could have an option such as `.CPPClass` to force class mangling instead of struct mangling. And if there were a vtable then you'd have to manage its layout yourself...
