### ISSUE TITLE
Unable to implicitly cast 'System.Int' to 'int'

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#30]
`private const int DefaultSize = (Int)(1024 * 16);`

I expected these two types could be used interchangeably (are they not the same?)

**Comment by bfiete** [comment]
They are not the same. "System.Int" is what's called a "typed primitive" (and I see was not covered in the docs). It's like a struct that's guaranteed to lower to a specific primitive type, but does not implicitly cast to that primitive (since that cast is from a more-specific to less-specific type). Typed primitives are useful for things like creating named index types - in C++ you might do "typedef int IndexType" but in BeefLang, "struct IndexType : int {}" adds type safety, unique overload resolution, and allows adding methods and interface conformance.

The corlib typed primitives for a given primitive (ie System.Int) is used in certain cases like boxing and generic conformance checks for primitives, but otherwise is not much different than what you do when rolling your own typed primitives.
