### ISSUE TITLE
If you implement the <=> operator on a class, it may break List.Remove for that type

### ISSUE THREAD

**Issue by MattThorson** [beefytech/Beef#311]
For example,

```
public class A
{
    public int Priority;
    
    static public int operator<=>(Entity a, Entity b)
    {
        return a.Priority <=> b.Priority;
    }
}
```

If you call List.Remove on an instance of class A, the list will remove the first instance it finds that shares the same value of Priority as that instance, which may or may not be the instance you specified.

**Comment by bfiete** [comment]
Returning 0 from <=> means that you consider the values to be equal, like in the case of a string comparison. You could define an == operator to "fix" this, but I would consider it odd if your <=> operator returned zero but your equal operator returned false for the same inputs. 

In this case I don't think you want to use the <=> operator this way - if it's just for sorting then pass in a sort delegate to List.Sort (if that's what you're using).

**Comment by bfiete** [comment]
Actually - you're on to something here. There should be two ways to remove reference-type items from lists: one based on identity (address) and one based on user-defined equality (operator overloads)... Let me ponder this further.

**Comment by MattThorson** [comment]
Ah yeah, this would break any == checks I do in the same way, I hadn't considered that. But I could see it being useful to add the identity equality operators (=== and !==).

**Comment by bfiete** [comment]
FWIW - in C# the List calls the Object.Equals virtual method, which by default performs an identity equality check, but things like String override it to perform a string comparison. So technically there's no way to remove an exact instance of a string from a list in C#, but generally no one notices because strings are immutable anyway.

In Beef that's more problematic because you generally want to remove a specific instance of a string...

**Comment by bfiete** [comment]
We now have the === and !== strict equality operators. For objects it means reference equality, and for value types such as structs and tuples it means member-wise strict equality checks. And `List<T>` now has strict-equality versions of methods such as `RemoveStrict`.

**Comment by bfiete** [comment]
Also of note- I've done some work in the "other direction" in the standard library, proving "alternate key" versions of methods like "RemoveAlt<TAlt>" which allows you to pass an "alternate" compatible key, provided it hashes the same and there's a == overload available. This allows you to lookup items in a `Dictionary<String, Item>` with a `StringView` instead of having to construct a temporary `String` just for lookup, for example.
