### ISSUE TITLE
Generic method behaving weirdly

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#313]
In the following code you can see that If you try to call a generic method with another generic method the IDE complains: `Unable to determine generic argument 'T'`
But if you uncomment the commented function, the code compiles just fine, and the previously commented function doesn't even end up called.

```
using System;
using System.Collections;

namespace test3
{
	class Class1
	{
		//public bool Method1<T>(T param1)
		//{
		//	return false;
		//}

		public bool Method1<T>(List<T> param1)
		{
			return true;
		}
	}

	class Program
	{
		public static void CallMethod1<T>(Class1 c, T param1)
		{
			Runtime.Assert(c.Method1(param1));
		}

		public static void Main()
		{
			Class1 c = scope Class1();

			List<int> i = scope List<int>();
			CallMethod1(c, i);

			Console.WriteLine("Everything ok!");
			Console.In.Read();
		}
	}
}
```

_Note:_
If you call the Method1 directly in the Main, no error happens even with the original code.

**Comment by bfiete** [comment]
Unlike C#, BeefLang allows generic specialization to call more specific methods than the method matched by the generic definition.

```C#
public static void Write(Object val) {}
public static void Write(float val) {}
public static void Write(int val) {}

public static void Write<T>(T val)
{
    Write(val);
}
```

In this example, Write(Object) is required by the `Write<T>` definition because anything can be converted into an Object implicitly, but if you call `Write<T>` with a float or an int then those more-specific methods will be the ones actually called.

**Comment by Igoorx** [comment]
Thanks for the explanation, if there was any way for you to make the compiler simply raise an error if it didn't find a method to call, I think it would be better, as it currently forces me to create a method that I don't need just to make the call work, but no problem if it is not possible or if you want to leave it that way.

**Comment by bfiete** [comment]
Yes, the thing you posted is a bug.

As for your question about "simply raise an error if it didn't find a method to call" - this goes to the heart of how generics work. The point is that you supply generic constraints and those constraints are checked directly at the callsites. This part of why generics are much more usable than the template-based approach of C++ where errors are only "late-bound", meaning errors occur within the implementation of a method rather than at the callsite of a method.

`Program.CallMethod1` is claiming that it will work on ANY type. This is a promise it makes. But then you're suggesting that you want it to fail at compile time if you pass in any other type besides a List. If this method is only capable of being invoked with a List then you must specify that in its constraints. If you absolutely don't want to do that then you can unconstrain it with 'var' but that's generally a bad idea.

**Comment by bfiete** [comment]
Just to be clear:
In C# your `Method1<T>(List<T> param1)` will NEVER be called because the `Program.CallMethod1` method will ALWAYS bind to `public bool Method1<T>(T param1)`.

**Comment by Igoorx** [comment]
Actually, my real implementation has other methods besides the list one, so I can't really constrain the generic method, but I would be happy to unconstrain it with 'var', but even so, the compiler doesn't accept the code.
Example: http://prntscr.com/sr6jlb

**Comment by bfiete** [comment]
Ah, yeah, what you posted is a var bug. That should have been allowed.

**Comment by Igoorx** [comment]
Oh nice, that makes sense, I will wait for the fix then :)
Here are the codes I used for the 2 bugs:
<details>
<summary>Code Bug "Ambigous method call"</summary>

```
using System;
using System.Collections;

namespace test3
{
	class Class1
	{
		public bool Method1<T>(ref T param1)
		{
			return false;
		}

		public bool Method1<T>(ref List<T> param1)
		{
			return true;
		}
	}

	class Program
	{
		public static void CallMethod1<T>(Class1 c, ref T param1)
		{
			Runtime.Assert(c.Method1(ref param1));
		}

		public static void Main()
		{
			Class1 c = scope Class1();

			List<int> i = scope List<int>();
			CallMethod1(c, ref i);

			Console.WriteLine("Everything ok!");
			Console.In.Read();
		}
	}
}
```
</details>

<details>
<summary>Code Bug in generic unconstraint</summary>

```
using System;
using System.Collections;

namespace test3
{
	class Class1
	{
		//public bool Method1<T>(T param1)
		//{
		//	return false;
		//}

		public bool Method1<T>(List<T> param1)
		{
			Console.WriteLine("List");
			return true;
		}

		public bool Method1<K, V>(Dictionary<K, V> param1) where K : IHashable
		{
			Console.WriteLine("Dict");
			return true;
		}

		public bool Method1<K, V>(Tuple<K, V> param1) where K : IHashable where V : IHashable
		{
			Console.WriteLine("Tuple");
			return true;
		}
	}

	class Program
	{
		public static void CallMethod1<T>(Class1 c, T param1) where T : var
		{
			Runtime.Assert(c.Method1(param1));
		}

		public static void Main()
		{
			Class1 c = scope .();

			List<int> i = scope .();
			CallMethod1(c, i);

			Dictionary<bool, int> d = scope .();
			CallMethod1(c, d);

			Console.WriteLine("Everything ok!");
			Console.In.Read();
		}
	}
}
```
</details>

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/fa7792650c6fb4c7f56185c7545a8f1e1167da79 and https://github.com/beefytech/Beef/commit/d8f741e779333996f9e9ce7d78407ddbb41fe965
