### ISSUE TITLE
[Bug] IDE crashes when removing closing brace

### ISSUE THREAD

**Issue by RogueMacro** [beefytech/Beef#353]
I.e. in an if statement:
```cs
if (true)
{
}
```
I remove the closing brace:
```cs
if (true)
{

```
The IDE crashes.

Dump:
https://filebin.net/a7gnapegqn81n6ul

**Comment by bfiete** [comment]
What's really happening is that everything below that becomes a local method because of the brace mismatch, and then there's an error involving those local methods.

The easiest way for me to reproduce it would be if you sent the current code for this project to me (beef@beefytech.com), if you're willing to.

**Comment by RogueMacro** [comment]
I'm sorry, but I didn't see your comment before now and have changed my project a lot so I can't reproduce the problem. However, I can show you another bug I just discovered. I'll send you the project now. The problem occurs when changing the constructor of Grill.CLI.CommandEntry to a generic constructor, i.e.
Changing this:
```cs
public this()
{
}
```
to this:
```cs
public this<T>()
{
}
```

**Comment by bfiete** [comment]
Oh, well the fact that you were allowed you declare a constructor as a generic method is already the bug!

**Comment by bfiete** [comment]
I managed to reproduce your original error, fixed at https://github.com/beefytech/Beef/commit/5bdaeadc258b69430d81968d9fce0cc45c341faa

And the generic ctor is now properly disallowed at https://github.com/beefytech/Beef/commit/c4544f67d396ee7d5708694d3532ca0eeb1b00d6
