### ISSUE TITLE
MethodInfo Invoke parameter bugs

### ISSUE THREAD

**Issue by MattThorson** [beefytech/Beef#356]
Hopefully this one isn't user error on my end, but MethodInfo.Invoke doesn't seem to accept correct parameters.

```
[Reflect]
class Program
{
	public static int Main(String[] args)
	{
		let method = typeof(Program).GetMethod("Test").Value;
		method.Invoke(null, scope Object[] { });	// <-- Param Count Mismatch error

		let method2 = typeof(Program).GetMethod("Test2").Value;
		method2.Invoke(null, scope Object[] { 0 });	// <-- Invalid Argument (0) error

		return 0;
	}

	[Reflect, AlwaysInclude]
	public static void Test()
	{
		//Not reached
	}

	[Reflect, AlwaysInclude]
	public static void Test2(int i)
	{
		//Not reached
	}
}
```

**Comment by Jonathan-Racaud** [comment]
Hi,

The problem is with how you use the Invoke method. You should pass your parameter as you would normally do when calling the Test and Test2 methods.

See:
```c#
[Reflect]
public class Program
{
	public static void Main()
	{
		let method = typeof(Program).GetMethod("Test").Value;
		method.Invoke(null);

		let method2 = typeof(Program).GetMethod("Test2").Value;
		method2.Invoke(null, 0);
	}

	[Reflect, AlwaysInclude]
	public static void Test()
	{
		//Not reached
		var j = 0;
		j++;
		return;
	}

	[Reflect, AlwaysInclude]
	public static void Test2(int i)
	{
		//Not reached
		var j = i;
		j++;
		return;
	}
}
```

I added some code inside the Test and Test2 method just to see that the parameters were succesfully passed.

The ```params Object[] args``` in the Invoke method declaration does not expect you to pass an Object[]. If you come from C or C++ it behave like varargs would (if I'm not mistaken).

**Comment by bfiete** [comment]
Yes, this is correct. 

If you actually did want to pass through an array directly to a `params` parameter, you can do so by using a `params` expression at the callsite: `method.Invoke(null, params argArray);`

**Comment by MattThorson** [comment]
My mistake, thanks for the help :)
