### ISSUE TITLE
Ref is working with a temporary (and incorrect) value

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#381]
This code works fine, but I think it shouldn't because the parameter of Test1 is a reference to a temporary value, and isn't explicitly convertible from a numeric type.

```
		struct Struct1
		{
			int i;
		}

		public static void Test<T>(ref T a) where T : operator explicit INumeric
		{
			Type type = a.GetType();
			Console.WriteLine("{} {}", type, typeof(T));
		}

		public static void Main(String[] args)
		{
			Test(ref Struct1());

			Console.WriteLine("End.");
			Console.In.Read();
			return;
		}
```

**Comment by bfiete** [comment]
Just so I understand here- I see two bugs
1) The constraint of being convertible from INumeric should have failed at the `Test(ref Struct1())` callsite
2) System.Type does not implement ToString

I don't see a problem with being able to passing a ref to a temporary value, however. It's legal in C also...

**Comment by Igoorx** [comment]
@bfiete Actually I didn't notice the lack of the ToString, but you're completely right about this (Now I understand why It just prints `TypeInstance@...`). about the temporary value thing, I just assumed this is unintended behaviour because it doesn't work for builtin types, example:
![image](https://user-images.githubusercontent.com/14041768/86187669-b6dd8e00-bb12-11ea-912e-9839ea5be44e.png)

**Comment by bfiete** [comment]
Ah. Well- #1 is actually  a bit more complicated. It turns out the cast-from-INumeric constraint IS actually satisfied. A cast from an interface instance to a struct is just an unboxing. You may say that "Hey, Struct1 does not implement INumeric so it could never be unboxed from an INumeric", BUT we could derive a Struct2 from Struct1 that does implement INumeric, and then that unboxing could be legal.

**Comment by bfiete** [comment]
As far as the "temporary values", this is sortof like rvalues in C++. The purpose is to avoid some copying in the front-end, but it was also being used to try to protect a user from doing a "ref" on a temporary return value and thinking that the ref actually refers to a mutable "source value" inside the caller. Those should be different concepts, though...

**Comment by bfiete** [comment]
The issue with your other examples is that they are all constant values so you can't take addresses of them. BUT, now you can do `ref int[2](a, b)` because that is not a constant value. That is fixed at https://github.com/beefytech/Beef/commit/a2a1b486a28836fd228254ce0480b7087161a249, and also the Type.ToString is added.

**Comment by Igoorx** [comment]
@bfiete Thank you, but about the INumeric constraint, isn't there any way around it like making Struct1 sealed so it couldn't be derived by anything?

**Comment by bfiete** [comment]
You could just use the normal `where T : INumeric` interface constraint... that does not work in this particular case though?

**Comment by Igoorx** [comment]
Hm... My initial intention was to also allow types like Enums (that can be explicitly converted from INumeric), but yeah, I can add a System.Enum constraint.
