### ISSUE TITLE
uint.Parse and int.Parse: error in implementation ?

### ISSUE THREAD

**Issue by Jonathan-Racaud** [beefytech/Beef#389]
Hi,

the implementation for ``UInt.Parse`` uses ``UInt64.Parse`` when the ``sizeof(self)`` is different than ``uint64``:
```c#
public static Result<uint, ParseError> Parse(StringView val)
{
	if (sizeof(Self) == sizeof(uint64))
	{
		var result = UInt64.Parse(val);
		return *(Result<uint, ParseError>*)&result;
	}
	else
	{
		var result = UInt64.Parse(val);
		return *(Result<uint, ParseError>*)&result;
	}
}
```

Shouldn't it be ``UInt32.Parse(val)`` instead ? The implementation for ``Int.Parse`` uses ``Int32.Parse`` in that case.

Also ``Int.Parse`` does not uses ``sizeof(Self)`` but ``sizeof(int)``:
```c#
public static Result<int, ParseError> Parse(StringView val)
{
	if (sizeof(int) == sizeof(int64))
	{
		var result = Int64.Parse(val);
		return *(Result<int, ParseError>*)&result;
	}
	else
	{
		var result = Int32.Parse(val);
		return *(Result<int, ParseError>*)&result;
	}
}
```

Is there a difference in that case ?

**Comment by bfiete** [comment]
Yep, it should have called `UInt32.Parse` there. A lot of the int implementation methods use `Self` instead of their actual name just so their implementations exactly match character-by-character (to reduce mistype bugs when copying and pasting various implementations around to the various types, for one). Here it doesn't really matter but still the choice should have been consistent between these two methods. Anyway- fixed now...
