### ISSUE TITLE
IOpNegatable: Cannot perform binary operation '-'

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#41]
The full error is:
ERROR: Cannot perform binary operation '-' between two instances of type 'T'.
Some sample code to demonstrate the problem. I understand IOpNegatable only takes 1 parameter.

```
	public struct MyRect<T> where T : IOpNegatable,
	{
		private T x;
		private T y;
		private T width;
		private T height;

		public static MyRect<T> fromTLBR(T top, T left, T bottom, T right)
		{
			return MyRect<T>(left, top, (right - left), (bottom - top));
		}

		public this(T x, T y, T width, T height)
		{
			this.x = x;
			this.y = y;
			this.width = width;
			this.height = height;
		}
	}
```

To remedy this I changed the interface to similar to IOpAddable:

```
	interface IOpNegatable2
	{
		static Self operator-(Self lhs, Self rhs);
	}
```

**Comment by Ruzihm** [comment]
Shouldn't it rather be a different interface such as `IOpSubtractable` ? `IOpNegatable specifically defines the unary negate operator, e.g.:

    IOpNegatable x = (Float)5.0;
    IOpNegatable y = -x;

    Console.Write("{}", (Float)y);

Which... actually doesn't even compile because "Operator can only be used on numeric types". What's with that?

**Comment by damianday** [comment]
Agreed after giving a bit more thought a new interface IOpSubtractable is the correct approach

**Comment by bfiete** [comment]
But, yes- @Ruzihm did find a different issue- there are not good error messages for attempting to invoke an operator overload dynamically from an interface. These interfaces were meant only to be used as generic constraints, not for dynamic dispatch.

The issue is that the return type from these operator overloads is 'Self'. This is not allowed since 'Self' infers the type implementing this interface (the concrete type). If you are dynamically calling a Self-returning interface method on a boxed valuetype, then that return value would have to be boxed by the callee --- which I thought I couldn't allow since it infers heap allocation that no one will know to clean up, but now I realize it COULD be implemented with a side stack.

So, better error message for now, but dynamic dispatch for operator overloads is going in the "future features" pile - but with a fairly low priority.
