### ISSUE TITLE
Compiler segfault on generic method with delegate as argument 

### ISSUE THREAD

**Issue by lukpank** [beefytech/Beef#44]
In the following program the compiler segfaults in
`BfModule::GetGenericParamInstance` on dereferencing `mMethodInfoEx`
which is `null`.  The problem is in the line marked with `// issue` and
there is no problem in the previous line which uses delegate stored
in a local variable.

(It would be nice feature if compiler could determine generic argument `T`
from the delegate to omit explicit `<String>`).

```csharp
using System;

namespace Issue
{
	class Program
	{
		public static int Main(String[] args)
		{
			var p = scope Program();
			delegate void(String v) dlg = scope => p.Method;
			p.Generic<String>(dlg);
			p.Generic<String>(scope => p.Method); // issue
			return 0;
		}

		public void Generic<T>(delegate void(T v) dlg)
		{
		}

		public void Method(String v)
		{
		}
	}
}
```

**Comment by bfiete** [comment]
Fixed in https://github.com/beefytech/Beef/commit/7b9c994066412b6a270fe72090372cd2ba42ec13
Will be in build 0.42.2.

The compiler can now infer the generic argument for "p.Generic(dlg);" but it cannot for "p.Generic(scope => p.Method)". Note that C# will also not infer generic arguments for this kind of case. One issue is that if you added ANY overload of "Method" then the inference would immediately break.
