### ISSUE TITLE
Few language inconsistencies

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#448]
- [ ] You can't cast to `double*` from `void*`. Ex: `((double*)(void*)x)[0] = 0.0;` 
- [ ] Int is missing MaxValue and MinValue where as uint has it.
- [ ] There doesn't appear to be a way to mark a simple property getter `=>` with `[Inline]`, you must change it to `{ [Inline] get{ } }`
- [ ] Negate operator allows a single arg to negate it but `+` operator requires 2 params. I'm assuming in most cases this results in a NOP as you just return the original value which is why its not there.
- [ ] Double is missing IsFinite
- [ ] It looks like you can substitute `{ }` for `( )` when initializing an array, Ex: `new .[] { 1, 2, 3 }`, this fails on a multi array `new .[,] { { 1, 2 }, { 3, 4} }`. If you swap it to `{ (1, 2) , (3, 4) }` it will work.

**Comment by bfiete** [comment]
Great stuff- these are all valid points.

**Comment by bfiete** [comment]
What is 'x' where `((double*)(void*)x)[0] = 0.0;` doesn't work? I haven't been able to reproduce this issue from the description.

**Comment by xposure** [comment]
I was trying to get a pointer to `this` and figured this was the closest way to achieve that.

```
	    [Ordered, Packed, CRepr]
		public struct Test
		{
			public double x;
			public double y;
			public double z;


			public int this[int index]
			{
				get
				{
					return ((double*)(void*)x)[0];
				}
			}
		}
```

**Comment by xposure** [comment]
![image](https://user-images.githubusercontent.com/6292318/91641099-3f33be80-e9f0-11ea-84cb-317d0930c8a6.png)

**Comment by bfiete** [comment]
I think you meant:

```C#
public double this[int index]
{
	get
	{
		return ((double*)(void*)&x)[index];
	}
}
```

And then you get the error:
`Cannot take address of field 'Test.x' within struct method 'Test. get accessor'. Consider adding 'mut' specifier to this method.`

That's because non-mut methods do not have an addressable 'this', as 'this' is passed as an immutable value (and actually on X86 will be passed via XMM0..2 when not inlined).

This is what you want:
```C#
public double this[int index]
{
	get
	{
		var val = this;
		return ((double*)(void*)&val.x)[index];
	}
}
```

The copy can be elided by the backend optimizer when the indexer gets inlined. You probably want to specify `[Inline]` on that method or otherwise it will only get inlined if you're doing link-time optimization (ThinLTO).

Also, Ordered/Packed/CRepr aren't going to do anything here- those only do something if the member spacing has alignment holes.

**Comment by xposure** [comment]
Hrm, I thought `&` only return the address as an `int`, so it actually returns a pointer instead? This does look like what I was going for though. 

The attributes were just copied from the math library I'm working on for OpenGL.

**Comment by bfiete** [comment]
All these issues (minus the casting thing discussed above) will have fixes in the next nightly build.

The legacy brace-initializer syntax creates a warning now, and it can be replaced by parens with reformat or with a fixit (ctrl+.).
