### ISSUE TITLE
Compile time codegen

### ISSUE THREAD

**Issue by LoopyAshy** [beefytech/Beef#454]
This is a feature I absolutely adore in programming languages, such as: Rust's procedural macros, or even something similiar to c#'s "Text Templates"; this has made my life soo much easier in the past regarding writing features such as json/xml to class convertors, or compile time errors (for example if the value is outside of a range), this however can still be achieved in beef via an external script which would have to be wrote myself, but considering this feature is getting more common in language's by default, it could be an attractive inclusion, and allow for very impressive features to be built from it..

**Comment by bfiete** [comment]
There a "feature tracking" issue intended for this here: https://github.com/beefytech/Beef/issues/408

I do think metaprogramming support is going to look more like fancy code generation rather than macros or general compile-time execution. The key issue to avoid is unbounded execution time from user code during "code intellegence" passes like refactoring/autocomplete. Code generation solves that issue by breaking out the compile-time-execution phase into an explicitly requested operation that can be aborted (and easily timed, profiled, and debugged).

**Comment by LoopyAshy** [comment]
As long as it is powerful enough to achieve things such as generating serialization layouts and such, it shall be quite beautiful if I say so myself, serialization is one of my main uses for such a feature.

**Comment by LoopyAshy** [comment]
Due to this being a duplicate I will close this.
