### ISSUE TITLE
Differentiate structs from classes within the IDE

### ISSUE THREAD

**Issue by LoopyAshy** [beefytech/Beef#455]
This is mostly just a feature I desire while coding in both C# and Beef: for the IDE to make structs and classes visually different even if it is only a syntax colour difference, the reasoning for this is due to how different classes and structs actually are within those 2 languages, Such as the simple fact that structs are passed by value and not reference unless explicitly instructed, this would make reading over the code much more pleasant as far as I am aware.
I have also noticed that the IDE when highlighting types and variables, also does not state if they are structs or classes without actually going to the source, which when working with people on the same codebase can get tedious.

**Comment by LoopyAshy** [comment]
Perhaps this can also be extended to whether the object's are initialised on the heap or the stack, which would make memory management even easier than it is currently, and would make the understanding of where the object is currently stored very clear to the programmer and any one else who reads the code.

**Comment by bfiete** [comment]
I've been testing out a new color scheme the past few weeks that does differentiate between structs, classes, and interfaces. I thought it might be too noisy, but I think I'm going to make it official soon. You're right that mouseover that's display type should also indicate the kind of type as well.

As for the heap vs stack, the debugger already displays whether values are stack or heap allocated:
![image](https://user-images.githubusercontent.com/3042917/91981968-6c2ced80-ecde-11ea-9382-dee2eb22b609.png)

But there is no way to annotated that code itself since that information is associated with a value, not a variable. And, in fact, you could assign a String to a heap-allocated variable in one place and the assign the same string to a heap-allocated variable directly afterwards.

**Comment by LoopyAshy** [comment]
I am glad to see they are being differentiated, regarding the code being identified as stack or heap that is very true about fact the variable could change, and I did think of that later on while going to sleep.

**Comment by bfiete** [comment]
Colorization added here: https://github.com/beefytech/Beef/commit/37f73f33457c8ba7603fbdb92f1eb0b810cdc96f
Type icons for code mouseovers added here: https://github.com/beefytech/Beef/commit/70c7067bb07050a3296925870ea04726f9263dbb
