### ISSUE TITLE
[Discussion] Boxing

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#457]
I've noticed with a lot of developers working with c# and even in interviews, a lot of people aren't aware of when something is boxed (or the issue with boxing). Since this language is geared towards game dev, boxing could have adverse effects inside tight loops.

- So my question is, should we consider showing when a call site is going to be boxed? 
- Perhaps a compiler flag to warn/error on boxing and then you can use the preprocessor to skip checks at certain code lines that are unavoidable?
- Perhaps showing a different color to a boxed callsite?

For reference, I'm referring to something like this https://www.beeflang.org/docs/language-guide/interfaces/

**Comment by bfiete** [comment]
Boxing occurs on the stack by default and it's actually very fast. Generally if you have a call that needs to be even MORE performant then you want that call to be to a generic method, but that's not really a callsite issue... 

I don't think you'd want to make warnings on just normal boxing because it happens all the time on innocent format-style calls like `Console.WriteLine` and `String.AppendF`.

Anyway- yeah, boxing can be a GC destroyer in C# but it's not a big issue in Beef. Well, unless you want to start storing boxed values long-term and then you must allocate them on the heap, but generally you want to use some like Variant for that anyway.

**Comment by xposure** [comment]
If you have a class reference in Beef and store a struct by interface in that class, how would the boxing occur then? I assume it would still happen at the callsite on the stack?

**Comment by bfiete** [comment]
Yeah- the boxing will happen at the callsite on the stack. In debug mode that object will be marked as deleted at the end of the scope (exit of the method) and if you access it before the stack gets overwritten then you will get a runtime error for a deleted stack object (annotated with the code location of the stack allocation). Otherwise you just get stack garbage. A side-stack feature is planned for debugging which will make nearly-guaranteed the boxed object won't be overwritten before it can (correct) cause the "stack object deleted" runtime error.

In general, interface pointers are more of a 'code smell' type thing in Beef than in C#, I suppose.
