### ISSUE TITLE
[BUG] Crash while debugging

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#489]
I was using hot reload and made a change with a break point. When I rebuilt the IDE said this file was changed or whatever and it was showing an older file that was colored slightly different. After trying to get it to show the new file where I made the changes and rebuilt it a few times, I gave up and closed the window with ctrl+w where it asked if I wanted to save the changes and I said no.

[crash-while-debug.zip](https://github.com/beefytech/Beef/files/5228082/crash-while-debug.zip)

**Comment by bfiete** [comment]
Just to explain what was going on there though: when you made a hot code change, the old method is still executing - it doesn't just "switch over" to the new code until the next time it's called. That's why you see the old code still, because that's the code that's actually executing still.

Still, the crash is a bug of course.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/7fdce4b5af29869fd524694ec6fda3149d6f94a2

**Comment by xposure** [comment]
To be clear, IIRC the docs say it swaps out the function pointer, so I would actually have to leave the entire function and re-enter it to get the new code correct?

**Comment by bfiete** [comment]
Yeah, you have to re-enter to get the new code. It basically just inserts a jump to the new function location at the start of the old function's code.
