### ISSUE TITLE
[BUG] Trying to implement linq style operators

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#556]
- The editor is showing the wrong method being selected, for example if you do `list.Max( (x) => x.Width);` intellisense takes you to the base method and not the overloaded method with the delegate.

- The editor will crash a lot randomly with different combinations of the below file. Try commenting out different methods and I suggest having Program.cs with some sort of List<struct> and accessing a property/field on the struct via delegate.

```
using System.Collections;
namespace Atma.Framework
{
	public static
	{
		public static K Min<T, K, F>(this List<T> items, F dlg )
			where bool : operator K < K
			where F : delegate K(T item)
		{
			var first = true;
			K current = default;
			for (var it in items)
			{
				let r = dlg(it);

				if (first)
				{
					current = r;
					first = false;
				}
				else if (r < current)
				{
					current = r;
				}
			}

			return current;
		}
		
		public static T Min<T>(this List<T> items)
			where bool : operator T < T
		{
			var first = true;
			T current = default;
			for (var it in items)
			{
				if (first)
				{
					current = it;
					first = false;
				}
				else if (it < current)
				{
					current = it;
				}
			}

			return current;
		}

		public static K Max<T, K, F>(this List<T> items, F dlg )
			where bool : operator K > K
			where F : delegate K(T item)
		{
			var first = true;
			K current = default;
			for (var it in items)
			{
				let r = dlg(it);

				if (first)
				{
					current = r;
					first = false;
				}
				else if (r > current)
				{
					current = r;
				}
			}

			return current;
		}

		public static T Max<T>(this List<T> items)
			where bool : operator T > T
		{
			var first = true;
			T current = default;
			for (var it in items)
			{
				if (first)
				{
					current = it;
					first = false;
				}
				else if (it > current)
				{
					current = it;
				}
			}

			return current;
		}

		public static mixin Max(var items)
		{
			var current = items[0];
			for(var i = 1; i < items.Count;i++)
			{
				if (items[i] > current)
				{
					current = items[i];
				}
			}

			return current;
		}
	}
}
```

[crash-max.zip](https://github.com/beefytech/Beef/files/5329774/crash-max.zip)

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/3b9558a5080e3bebda95b4828674caf421874d04

Also note that this:
```
public static K Max<T, K, F>(this List<T> items, F dlg )
			where bool : operator K > K
			where F : delegate K(T item)
```
Is under-constrained on 'K' when 'F' is a method bind (such as a lambda) because the requested method signature must be known in order to bind to begin with.  This is why you can't just do `var = new (x) => x + 1` (not in C# either). In other words, there's no way to infer the generic argument so the method will not be selected.

You'd have to create a utility class to do this, so you could do a `ListHelper<K>.Max(items, (x) => x + 1)` so that `K` can be explicitly specified and `T` and `F` can be inferred.

This is sufficiently constrained, however:
```
public static K Max<T, K, F>(this List<T> items, F dlg )
			where F : delegate T(T item)
```
