### ISSUE TITLE
partial class support partial  keyword

### ISSUE THREAD

**Issue by sgf** [beefytech/Beef#603]
partial class support
why:
better for manage source code

**Comment by bfiete** [comment]
There are type extensions, which do everything you can do with a partial class. Is there some use case that doesn't cover?

**Comment by sgf** [comment]
access private 

> There are type extensions, which do everything you can do with a partial class. Is there some use case that doesn't cover?

does  type extensions can access private Field ?

The partial keyword is usually used when a single file is too large, for example, a single file exceeds 1000 lines, which is divided into multiple files, which is convenient for developers to quickly find the implementation based on the file.

**Comment by bfiete** [comment]
Yes, you can access private fields. 

The only feature that isn't _obviously_ supported is partial methods with optional implementations (if you don't declare an implementation then method calls to that method will be skipped), but this actually is supported:
In the main type definition you can declare a method such as `[SkipCall] extern void TestMethod();`, and then if you define a replacement method in an extension then that replacement will be called, otherwise no method will actually be called because of the original method with the `[SkipCall]` attribute.

Anyway, yeah, just split your type up amongst a bunch of files and have one master definition and extensions in the other files.

**Comment by rds1983** [comment]
It is possible to make a single large static class that spans over multiple files in Beef?

I develop a library called StbImageSharp, which is C# port of stb_image.h: https://github.com/StbSharp/StbImageSharp/tree/master/src

As you can see it's basically one large static class StbImage that spans over many files (StbImage*.cs).
StbImage.Generated.*.cs were generated using special tool.
While StbImage.cs was made manually.

Right now, I consider making StbImageBeef.
Hence the question in the beginning of this post.

**Comment by bfiete** [comment]
@rds1983 Yes.
