### ISSUE TITLE
[BUG] Dtor doesn't chain from extension

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#629]
e8ad5bd

The `leak` object in Texture won't have be freed if the extension class has a dtor.

**Comment by bfiete** [comment]
Chained destructors should work now https://github.com/beefytech/Beef/commit/b6db69d2b0c9f9fdefb0c40e5b0153d67fcac0eb

Field initializers should now work as expected in extensions, as well - they will get properly initialized no matter where the constructor is executing.

Constructors have the same visibility constraints (by design) as adding methods to an extension: they can't be called from a root project without a dependency.

I'm thinking about adding something that is part way between a field initializer and a constructor, though: an initialization block. A block of code that will always get executed after field initializers and before the explicit code in a constructor. That way you could just add initialization blocks to extensions without interfering with any constructors. This also solves a general issue when you have many constructors that need a common initialization, which currently requires you pull out that code into some kind of `Init` method and call it manually from each constructor.

ALSO- I also did the suggestion of warning when an extension adds a method override that conflicts with a method in the root type definition. That includes adding a new default constructor.

ALSO- there is now a way to call root methods from an override in the extension. `[NoExtension]`. IE:
`public new this() : [NoExtension]this() {}` defines a constructor that first calls to the root definition constructor.

This will all be documented for the next official release.
