### ISSUE TITLE
[BUG] Failed to inject mixin

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#643]
c9c6aad

```
ERROR: Failed to inject mixin 'SortByClosest!(var self, Atma.Math.int3 position, int depthBias = 4)' at line 165:5 in c:\Users\cphillipd83\Documents\Git\Beef\GameSim\src\EntitySystem\Zone.bf
    SortByClosest!(_zones, cell.Position);
    ^^^^^^^^^^^^^^
  > Unable to implicitly cast 'System.Comparison_jkelSVJElujw' to 'System.Comparison<GameSim.EntitySystem.Zone>' at line 38:13 in c:\Users\cphillipd83\Documents\Git\Beef\GameSim\src\Extensions.bf
   self.Sort(scope (a, b) =>
             ^^^^^^^^^^^^^^^^
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/8abb72939bd3a039cd55fa667ba13b44b8505f9e

Also, the SortByClosest would probably be better expressed as a generic method with an unbound generic parameter:
```C#
public static void SortByClosest<T>(List<T> self, int3 position, int depthBias = 4) where T : var
```

(note that this doesn't work in the current build - but it will in the next nightly)

A good rule of thumb is that a mixin should be used when you need to inject flow control (ie: injecting a return into the caller) or performing stack allocation within the caller. Otherwise there's no benefit over a normal method.
