### ISSUE TITLE
[Feature Request] Add support for const references when defining extern functions or function pointers

### ISSUE THREAD

**Issue by taxmancw** [beefytech/Beef#657]
Currently there is no way in Beef to specify return or argument function parameters as a const ref (it is not needed in regular Beef coding).
When using extern functions, this can cause issues with linking if [LinkName(.CPP)] is used, since the symbol names will not match when mangling is applied.

Suggestion: add C# style `in` parameter modifier and `readonly` return modifier as the equivalent of CPP `const &`

Example (will fail to link):
```
// CPP Code

namespace Example
{
    class MyClass
    {
    public:
        static int32_t Testy(const int32_t& value)
        {
            return value * 2;
        }
    }
}

// Beef Code

namespace Example
{
    class MyClass
    {
        [LinkName(.CPP)] extern public static Testy(ref int32 value);
    }
}
```

**Comment by bfiete** [comment]
Support added at https://github.com/beefytech/Beef/commit/fa0e712c2b2e350a9dd093db51278602ab3c6f38

```C#
[return: MangleConst]
public static extern ref float TestMethod([MangleConst]ref int32 val);
```

As for the implementation suggestion- there is no need for an "in" parameter modifier because all arguments in Beef are already implicitly "in": immutable references (or copies when a copy would be faster for small data).
