### ISSUE TITLE
IDE crash

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#68]
```
        public struct Vec2
	{
		public static readonly Vec2 zero = default(Vec2);

		private float _x;
		private float _y;

		public this(float x, float y)
		{
		    _x = x;
		    _y = y;
		}
	}

	public struct Particle
	{
	}

	public abstract class ParticleSystem
	{
	    protected Particle[]    _particles;
	    
	    public void Update(int index)
	    {
	        var pt = &_particles[index];
	    }
	    
	    public void SetVecs(float value = -0.05f, 
							Vec2 vec = Vec2(0, 300),
	                        			Vec2 vec1 = Vec2.zero,
							Vec2 vec2 = Vec2.zero)
	    {

	    }
	}
```
Not sure whats causing it, at first highlighting the 'pt' variable caused it to crash but after reducing it to an example it crashes after about 5 seconds of being open in the editor.
[crash.zip](https://github.com/beefytech/Beef/files/4271976/crash.zip)

**Comment by bfiete** [comment]
Fixed in https://github.com/beefytech/Beef/commit/81af04a1ce1ef7ac062042dd0ccd2caf80a27b94. Triggered by the attempted const evaluation of the "Vec2(0, 300)"default.

Also- you can make the "zero" member const instead of just readonly. "default" is allowed for const aggregates but "Vec2(0, 300)" is not const-evaluatable and thus cannot be used for a default parameter value. We follow the C# rule there that you have to create overloads for that kind of non-const default case.
