### ISSUE TITLE
[BUG?] (void* this) gives access violation

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#741]
I had the code below working fine when the `Update` method was static and it simply took in a `Foo2*` but I was curious if I could get it to work with `this` too. It seems something gets lots if the function signature is `void* this` instead of `Foo2* this`. This code seems sketchy but it should be able to work since `this` is nothing more than a ptr to data right?

```
class Program
	{
		public static int Main(String[] args)
		{
			Works();
			Breaks();
			return 0;
		}

		public struct Foo2
		{
			public int32 x;

			public bool Update(int32 dt) mut
			{
				x += dt;
				return x > 100;
			}
		}

		typealias FooFunc = function bool(Foo2* this, int32 dt);
		typealias BarFunc = function bool(void* this, int32 dt);

		public static void Works()
		{
			var bar = scope Foo2();
			FooFunc f = => bar.Update;

			while (!f(bar, 10))
			{
				Console.WriteLine(scope $"{bar.x}");
			}
		}

		public static void Breaks()
		{
			var bar = scope Foo2();
			FooFunc temp = => bar.Update;
			BarFunc f = (.)(void*)temp;

			while (!f(bar, 10))
			{
				Console.WriteLine(scope $"{bar.x}");
			}
		}
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/9d3e245f697678bbae1a7c7bf784b6e0ace9480e

This was due to some handling of zero-sized structs. If you create a struct without any members then it doesn't actually have an address, and its methods don't actually have a `this` pointer passed in. The `void* this` was being treated like a zero-sized struct so the signatures of those functions became incompatible. That's fixed now.

**Comment by xposure** [comment]
Sweet! I'll give it a spin now.

**Comment by xposure** [comment]
Verified and working! Thanks.
