### ISSUE TITLE
Assertion failed - Expression: castedTypedValue

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#77]
After opening my project using debug version of BeefIDE from https://github.com/beefytech/Beef/commit/701e43bf1f6c574d41368585f7b836161a411d13 I'm hitting an assert error, please see attached crash report and screenshot.

[crash.zip](https://github.com/beefytech/Beef/files/4315147/crash.zip)

**Comment by bfiete** [comment]
It looks like it's an error with a parameter with a default parameter. If you Ignore, does the compiler throw an actual error on any line that make sense?

**Comment by bfiete** [comment]
If you want to debug - you can attach to the crash processed with another instance of BeefIDE. In the call to GetTypedValueFromConstant, you can mouse over "methodInstance" and you should see the name of the method and the defining class. That method will have some sort of default parameter value which is causing the issue here...

**Comment by bfiete** [comment]
That's 'Debug/Attach to Process'...

**Comment by bfiete** [comment]
Ah I already found a case that does it - having a StringView with a default string value. Did you have that? Did that actually work before?

**Comment by damianday** [comment]
I have a StringVew data = String.Empty in my socket code that was unused but compiled before, I'll try and reduce and debug it later.

**Comment by bfiete** [comment]
This should be fixed here https://github.com/beefytech/Beef/commit/0a407b0913ff734eb1f35b3161d9461a54dc8ca1

**Comment by damianday** [comment]
Confirmed no longer crashes :)
