### ISSUE TITLE
[Enhancement] Support for SizedArray extensions

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#859]
Currently the only way to do something like an implicit cast to Span from float[5] is this code...

```
	public static {
		public static Span<T> ToSpan<T, K>(this T[K] it)
			where K: const int
		{
			return Span<T>(&it[0], K);
		}
	}
```

It would be nice to be able to do one of these, if not both.

```
	public extension SizedArray<T, CSize>
		where CSize: const int
	{
		public static explicit operator Span<T>(SizedArray<T, CSize> sizedArray)
		{
			return Span<T>(&sizedArray.mVal[0], sizedArray.Count);
		}
	}

	public extension Span<T>
	{
		public static implicit operator Span<T>(T[?] sizedArray)
		{
			return Span<T>(&sizedArray[0], sizedArray.Count);
		}
	}

```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/1e52dce7c476abe4ed7ec4e540ef1690a1687301

There were 2 issues
1) Sized arrays didn't search inside their wrapped type `System.SizedArray<T, CSize>` for conversion operators
2) We needed `ref` params for operators because otherwise small sized arrays (3 elements or less) get passed by value so taking the address of that is _not_ the address of the original sized array.
