### ISSUE TITLE
[LINQ] SelectMany has a methodref that fails to implicitly cast to another methodref

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#881]
beef.linq 40360cb3bb66e14bb6a7d4c583ed711c3a758501
beef 5677f27cacdc0a789eabed7cb0a086050949753e

**Comment by bfiete** [comment]
Ah, yeah, so here's what's going on here:
You can only use method references when the generic argument _can be inferred directly from the binding argument_.

You explicitly define the return type of SelectMany to be `SelectManyEnumerable<TSource, decltype(default(TCollection).GetEnumerator()), delegate decltype(default(TCollection2).GetEnumerator())(TSource), TResult, decltype(default(TCollection2).GetEnumerator())>`

So that explicit `delegate decltype(default(TCollection2).GetEnumerator())(TSource)` generic arg is the issue.

I think in general there's just no way to use method references in any way for return values.

So, yeah, the allocation is necessary.

**Comment by xposure** [comment]
+1
