### ISSUE TITLE
[LINQ] Iterator fails to chain dispose

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#887]
I have a feeling that something is happening with these chain calls and the `[SkipCall]` on the iterator's Dispose. For example this code has a memory leak, the call on WhereEnumerable.Dispose calls its iterator.Dispose which should call ReverseEnumerable's dispose but it doesn't. The debuger steps over it and never calls Reverse's dispose

```
		[Test]
		public static void HigCallingMutatingIssue()
		{
			int[] test1 = scope .(10, 11, 10, 12, 13, 14, -1);
			let actual = test1.Reverse().Where((x) => x > 0 && x % 2 == 0).Sum();

			Test.Assert(actual == 46);
		}
```

**Comment by xposure** [comment]
Related to 841

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/9afa24e5d757c17ba758fb3cf9d48c21a264baf0
This was interesting- `WhereEnumerable.Dispose` didn't have a `mut`, so the call to `mIterator.Dispose` should have failed since a non-mut `ReverseEnumerable.Dispose` isn't available. The method selector just picks the first Dispose it finds, expecting it to throw an error, which ends up being the `[SkipCall]` one, but the `[SkipCall]` bails out before the mut error is actually thrown.

It now properly displays the error, and then adding the `mut` to WhereEnumerable (+Enumerator) fixes the issue.
